PROVINCE_ALIASES = {
    "alava": "Álava",
    "albacete": "Albacete",
    "alicante": "Alicante",
    "almeria": "Almería",
    "asturias": "Asturias",
    "avila": "Ávila",
    "badajoz": "Badajoz",
    "barcelona": "Barcelona",
    "burgos": "Burgos",
    "caceres": "Cáceres",
    "cadiz": "Cádiz",
    "cantabria": "Cantabria",
    "castellon": "Castellón",
    "ciudad real": "Ciudad Real",
    "cordoba": "Córdoba",
    "cuenca": "Cuenca",
    "girona": "Girona",
    "gerona": "Girona",
    "granada": "Granada",
    "guadalajara": "Guadalajara",
    "guipuzcoa": "Gipuzkoa",
    "gipuzkoa": "Gipuzkoa",
    "huelva": "Huelva",
    "huesca": "Huesca",
    "illes balears": "Illes Balears",
    "islas baleares": "Illes Balears",
    "baleares": "Illes Balears",
    "jaen": "Jaén",
    "a coruna": "A Coruña",
    "la coruna": "A Coruña",
    "a coruña": "A Coruña",
    "la coruña": "A Coruña",
    "la rioja": "La Rioja",
    "las palmas": "Las Palmas",
    "leon": "León",
    "lleida": "Lleida",
    "lerida": "Lleida",
    "lugo": "Lugo",
    "madrid": "Madrid",
    "malaga": "Málaga",
    "murcia": "Murcia",
    "navarra": "Navarra",
    "ourense": "Ourense",
    "orense": "Ourense",
    "palencia": "Palencia",
    "pontevedra": "Pontevedra",
    "salamanca": "Salamanca",
    "santa cruz de tenerife": "Santa Cruz de Tenerife",
    "segovia": "Segovia",
    "sevilla": "Sevilla",
    "soria": "Soria",
    "tarragona": "Tarragona",
    "teruel": "Teruel",
    "toledo": "Toledo",
    "valencia": "Valencia",
    "valladolid": "Valladolid",
    "bizkaia": "Bizkaia",
    "vizcaya": "Bizkaia",
    "zamora": "Zamora",
    "zaragoza": "Zaragoza",
    "jaen provincia": "Jaén",
    "cadiz provincia": "Cádiz",
    "madrid provincia": "Madrid",
    "barcelona provincia": "Barcelona",
}

LOCALITY_ALIASES = {
    "calpe": "Calp",
    "la coruna": "A Coruña",
    "a coruna": "A Coruña",
    "la coruña": "A Coruña",
    "gerona": "Girona",
    "lerida": "Lleida",
    "orense": "Ourense",
    "vich": "Vic",
    "sangenjo": "Sanxenxo",
    "santa cristina de aro": "Santa Cristina d'Aro",
    "cornella de terri": "Cornellà del Terri",
    "cornella de terri girona": "Cornellà del Terri",
    "caldas de estrach": "Caldes d'Estrac",
    "caldas de estrach barcelona": "Caldes d'Estrac",
    "benetuser": "Benetússer",
    "galdacano": "Galdakao",
    "galdácano": "Galdakao",
    "la nucia": "La Nucia",
    "san pedro de alcantara": "San Pedro Alcántara",
    "barcelona capital": "Barcelona",
    "madrid capital": "Madrid",
    "zaragoza capital": "Zaragoza",
    "valencia valencia": "Valencia",
    "murcia murcia": "Murcia",
    "valladolid valladolid": "Valladolid",
    "guadalajara guadalajara": "Guadalajara",
    "miguelturra ciudad real": "Miguelturra",
    "alcala de henares madrid": "Alcalá de Henares",
    "tres cantos madrid": "Tres Cantos",
    "villalbilla madrid": "Villalbilla",
    "torres de la alameda madrid": "Torres de la Alameda",
    "meco madrid": "Meco",
    "guadalix de la sierra madrid": "Guadalix de la Sierra",
    "arroyomolinos madrid": "Arroyomolinos",
    "algete madrid": "Algete",
    "becerril de la sierra madrid": "Becerril de la Sierra",
    "rozas de madrid las": "Rozas de Madrid, Las",
    "las rozas de madrid": "Rozas de Madrid, Las",
    "oliva la": "La Oliva",
    "franqueses del valles les": "Franqueses del Vallès, Les",
    "les franqueses del valles": "Franqueses del Vallès, Les",
    "castelldefels barcelona": "Castelldefels",
    "montmelo barcelona": "Montmeló",
    "sabadell barcelona": "Sabadell",
    "vic barcelona": "Vic",
    "granollers barcelona": "Granollers",
    "mataro barcelona": "Mataró",
    "igualada barcelona": "Igualada",
    "badalona barcelona": "Badalona",
    "castellar del valles barcelona": "Castellar del Vallès",
    "palma de mallorca": "Palma",
    "palma de mallorca baleares": "Palma",
    "ingenio las palmas": "Ingenio",
    "moron de la frontera sevilla": "Morón de la Frontera",
    "sanlucar de barrameda cadiz": "Sanlúcar de Barrameda",
    "ubeda": "Ubeda",
    "castellon": "Castelló de la Plana",
}